name: Generate Snake Game

on:
  schedule: # runs automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # allows you to run it manually

jobs:
  build:
    name: generate-snake-game-from-github-contribution-grid
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: EmilyPriyadarshini
          outputs: dist/snake.svg
          theme: dark

      - name: Push Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
